prompts = ["What is irrigation? State its sources and some traditional, modern methods of irrigation.", 
           "Explain fermentation and design an experiment which can be performed at home to observe it.", 
           "What are the constituents of petroleum and its uses?", 
           "What is calorific value with respect to fuels? List some popular fuels and their calorific values.", 
           "Explain the causes of deforestation.", 
           "How are test-tube babies made?", 
           "What are some myths about adolescence and puberty?", 
           "What is force? What is state of motion?", 
           "Explain friction by designing an experiment which can be done at home to understand it.", 
           "Name some Indian sound instruments and their vibrating parts which produce sound."
           ]

strats = ["",
           "Answer questions taking into account the following information to remove any ambiguity that may arise. I am a science teacher who teaches 6th class Indian students using the NCERT book who likes simplified, consistent answers of about 300 words.", 
           "Explore options and present the best answer. Work out the solution on your own before answering any yes/no questions presented to you. Check for any missed case before answering.", 
           "To answer any question: Step 1: Define and state all prerequisite knowledge required to understand your answer. Give a short explanation for each of these topics. Step 2: Answer the question using the enlisted prerequisites to obtain a clear and logical explanation.", 
           "Answer by only referencing the Class 6 NCERT textbook for science.", 
           "Answer questions taking into account the following information to remove any ambiguity that may arise. I am a science teacher who teaches 6th class Indian students using the NCERT book who likes simplified, consistent answers of about 300 words. Explore options and present the best answer. Work out the solution on your own before answering any yes/no questions presented to you. Check for any missed case before answering.", 
           "Answer questions taking into account the following information to remove any ambiguity that may arise. I am a science teacher who teaches 6th class Indian students using the NCERT book who likes simplified, consistent answers of about 300 words. To answer any question: Step 1: Define and state all prerequisite knowledge required to understand your answer. Give a short explanation for each of these topics. Step 2: Answer the question using the enlisted prerequisites to obtain a clear and logical explanation.", 
           "Answer questions taking into account the following information to remove any ambiguity that may arise. I am a science teacher who teaches 6th class Indian students using the NCERT book who likes simplified, consistent answers of about 300 words. Answer by only referencing the Class 6 NCERT textbook for science.", 
           "Explore options and present the best answer. Work out the solution on your own before answering any yes/no questions presented to you. Check for any missed case before answering. To answer any question: Step 1: Define and state all prerequisite knowledge required to understand your answer. Give a short explanation for each of these topics. Step 2: Answer the question using the enlisted prerequisites to obtain a clear and logical explanation.", 
           "Explore options and present the best answer. Work out the solution on your own before answering any yes/no questions presented to you. Check for any missed case before answering. Answer by only referencing the Class 6 NCERT textbook for science.",
           "To answer any question: Step 1: Define and state all prerequisite knowledge required to understand your answer. Give a short explanation for each of these topics. Step 2: Answer the question using the enlisted prerequisites to obtain a clear and logical explanation. Answer by only referencing the Class 6 NCERT textbook for science.", 
           "Answer questions taking into account the following information to remove any ambiguity that may arise. I am a science teacher who teaches 6th class Indian students using the NCERT book who likes simplified, consistent answers of about 300 words. Explore options and present the best answer. Work out the solution on your own before answering any yes/no questions presented to you. Check for any missed case before answering. To answer any question: Step 1: Define and state all prerequisite knowledge required to understand your answer. Give a short explanation for each of these topics. Step 2: Answer the question using the enlisted prerequisites to obtain a clear and logical explanation.", 
           "Answer questions taking into account the following information to remove any ambiguity that may arise. I am a science teacher who teaches 6th class Indian students using the NCERT book who likes simplified, consistent answers of about 300 words. Explore options and present the best answer. Work out the solution on your own before answering any yes/no questions presented to you. Check for any missed case before answering. Answer by only referencing the Class 6 NCERT textbook for science.", 
           "Answer questions taking into account the following information to remove any ambiguity that may arise. I am a science teacher who teaches 6th class Indian students using the NCERT book who likes simplified, consistent answers of about 300 words. To answer any question: Step 1: Define and state all prerequisite knowledge required to understand your answer. Give a short explanation for each of these topics. Step 2: Answer the question using the enlisted prerequisites to obtain a clear and logical explanation. Answer by only referencing the Class 6 NCERT textbook for science.", 
           "Explore options and present the best answer. Work out the solution on your own before answering any yes/no questions presented to you. Check for any missed case before answering. To answer any question: Step 1: Define and state all prerequisite knowledge required to understand your answer. Give a short explanation for each of these topics. Step 2: Answer the question using the enlisted prerequisites to obtain a clear and logical explanation. Answer by only referencing the Class 6 NCERT textbook for science.", 
           "Answer questions taking into account the following information to remove any ambiguity that may arise. I am a science teacher who teaches 6th class Indian students using the NCERT book who likes simplified, consistent answers of about 300 words. Explore options and present the best answer. Work out the solution on your own before answering any yes/no questions presented to you. Check for any missed case before answering. To answer any question: Step 1: Define and state all prerequisite knowledge required to understand your answer. Give a short explanation for each of these topics. Step 2: Answer the question using the enlisted prerequisites to obtain a clear and logical explanation. Answer by only referencing the Class 6 NCERT textbook for science."
           ]
